# Generated by Django 6.0.3 on 2026-05-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
    ]
