# Generated by Django 6.0.5 on 2026-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_equipo', '0002_alter_reserva_unique_together'),
        ('reservas_equipo', '0002_create_groups_and_permissions'),
    ]

    operations = [
    ]
