# Generated by Django 6.0.5 on 2026-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_equipo', '0003_merge_20260507_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='laboratorio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
    ]
